from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('InstructPLM/MPNN-ProGen2-xlarge-CATH42', trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained('InstructPLM/MPNN-ProGen2-xlarge-CATH42', trust_remote_code=True)

model.cuda().eval()
model.requires_grad_(False)

batch = tokenizer('Fast-PETase.pyd|1',return_tensors='pt').to(device=model.device)

tokens_batch = model.generate(
    **batch,
    do_sample=True,
    temperature=0.8, 
    max_length=512+tokenizer.n_queries,
    min_new_tokens=5,
    top_p=0.9, 
    num_return_sequences=5, 
    pad_token_id=0, 
    repetition_penalty=1.0, 
    bad_words_ids=[[3]]
    )

texts = tokenizer.batch_decode(tokens_batch)

def truncate_seq(text):
    bos = text.find('1')
    eos = text.find('2')
    if eos > bos and bos >= 0:
        return text[bos+1:eos]
    else:
        return text[bos+1:]
print([truncate_seq(t) for t in texts])

# Ref. Seq 
#       'MQTNPYARGPNPTAASLEASAGPFTVRSFTVSRPSGYGAGTVYYPTNAGGTVGAIAIVPGYTARQSSIKWWGPRLASHGFVVITIDTNSTLDQPESRSSQQMAALRQVASLNGTSSSPIYGKVDTARMGVMGWSMGGGGSLISAANNPSLKAAAPQAPWHSSTNFSSVTVPTLIFACENDSIAPVNSSALPIYDSMSQNAKQFLEIKGGSHSCANSGNSNQALIGKKGVAWMKRFMDNDTRYSTFACENPNSTAVSDFRTANCS'
# Designed seq:
#       'METNPFHRGPDPTCASLEAGAGPFNVQSFRVDRPLGFGAGTVFYPTDAGGQVPAIAIAPGFTQTQSSVMWYGPRLASHGFVVIVIDTISTFDNPDSRSAQLLAALDQVANLNSNASSPIYGKVDTTRQAVMGHSMGGGGSLISAMNNPSLKAAAPMAPWHVSTNFSAVQVPTFIIGAENDTIAPVASHSIPFYNSIPSSLPKAYMELAGASHLAPNSSNPTIAKYSISWLKRFVDNDTRYEQFLCPAPTSTALISEYRDTCPY', 
#       'EETNPYSKGPDPTAASLEASAGPFTVQSFSVARPLGFGAGTVYYPTDAGGKVGAIAVVPGYTDTQGSIRWWGPRLASHGFVVMTIDTISSYDQPDSRSAQLMAALDQLANLNSTSSSPIYNKVDTTRQAVMGHSMGGGGSLISAMNNPNLKAAIPMAPWHSSTNFSSVKVPTMILGAERDTVAPVSSHAEPFYNSLPSSTPKAYLELKGASHFFPNTTNTPTFAKSVLAWLKRFVDNDTRYEQFLCPGPTSTDLTDYRNTCPY', 
#       'SETNPYIKGPDPTAASLEASAGAFTVQSFTVSRPTGFGAGTVYYPTDAGGRVGAIAIVPGYTATQSSIKWWGPRLASHGFVVMTIDTNSTYDQPDSRANQLMAALDQLTNLNSTRSSPIYGKVDTTRQGVMGHSMGGGGSLIAAQDNPNLKAAIPLAPWHSSSNFSSVTVPTLIIGAQNDTVAPVSSHSIPFYTSLPSSLDKAYLELNGASHFAPNSSNTTIAKYSISWLKRFIDNDTRYEQFLCPPPSGSALISEYRNTCPY', 
#       'EETWPYHRGPDPTAASLEASAGPFTVQSFTVARPLGFGAGTVYYPTDAGGRVGAVAVVPGYTQTQSAIRWWGPRLASHGFVVMTIDTISTFDQPDSRSAQLLAALDQLAVLNSTRSSPIYNKVDTTRQGVMGHSMGGGGSLISAMNNPSLKAAVPLAPWHASTNFSNVQVPTLIIGASDDTTASVTTHSIPFYNSIPSSVPKAYLELQGQSHFCPNTSNTTIAKYSISWLKRFIDNDTRYDQFLCPPPNGSAISDYRSTCPH', 
#       'METNPFIRGPNPTAASLEASAGPFQVSSFSVARPVGFGAGTVYYPTDAGGQVPAIAIAPGFTQTQASVKWYGPRLASHGFVVIVIDTNSTLDNPDSRSAQLLAALDQVSTLNSSSSSPIYGKVDTTRQGVMGHSMGGGGSLISAQNNPALKAAIPLAPWHVSTDFSGVTVPTLIIGAENDTVAPVGTHAEPFYNSIPSSTPKAYLELNNASHFAPNTSNTTIAKYSIAWLKRFVDNDTRYDQFLCPAPNGNAIQDYRDTCPH'
#